Document: ts3client
Title: Debian ts3client Manual
Author: <insert document author here>
Abstract: This manual describes what ts3client is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/ts3client/ts3client.sgml.gz

Format: postscript
Files: /usr/share/doc/ts3client/ts3client.ps.gz

Format: text
Files: /usr/share/doc/ts3client/ts3client.text.gz

Format: HTML
Index: /usr/share/doc/ts3client/html/index.html
Files: /usr/share/doc/ts3client/html/*.html
